name: Release

on:
  pull_request:
    branches: [ main ] # TODO for testing only
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate Release AAB
      run: ./gradlew bundleRelease
    - name: Sign Android release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Upload Release AAB to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: Release AAB
        path: app/build/outputs/bundle/release/app-release.aab
    - name: Upload Release AAB to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ SERVICE_ACCOUNT_JSON }}
        packageName: com.louis993546.composecomposer
        releaseFile: app/build/outputs/bundle/release/app-release.aab
        track: beta